### ISSUE TITLE
Create account error

### ISSUE THREAD

**Issue by saivishnu725** [gskinnerTeam/flutter-folio#15]
[Got this error when i clicked on "Create an account?" button](https://instagram.fblr9-1.fna.fbcdn.net/v/t51.2885-15/fr/e15/s1080x1080/156174055_820620678551225_339463541952294212_n.jpg?tp=1&_nc_ht=instagram.fblr9-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=7t5vR7OLvwIAX-cEnF1&oh=036ac24ea19f66307c90605baaf6a18e&oe=606AE0FE&ig_cache_key=MjUyMTg4NTMyNjg5OTQ3OTM2MQ%3D%3D.2)

**Comment by mrmayurgithub** [comment]
> [Got this error when i clicked on "Create an account?" button](https://instagram.fblr9-1.fna.fbcdn.net/v/t51.2885-15/fr/e15/s1080x1080/156174055_820620678551225_339463541952294212_n.jpg?tp=1&_nc_ht=instagram.fblr9-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=7t5vR7OLvwIAX-cEnF1&oh=036ac24ea19f66307c90605baaf6a18e&oe=606AE0FE&ig_cache_key=MjUyMTg4NTMyNjg5OTQ3OTM2MQ%3D%3D.2)

I tried to solve this, it was happening because the TextEditingController is disposed everytime whene FormMode is changed.
In the **dispose** method ->

![folio](https://user-images.githubusercontent.com/58694295/109980958-762fb780-7d26-11eb-941f-0f208aa3facb.png)
But I am not sure commenting out this will be good or not, as I think the TextEditingController will never be disposed in the app.

**Comment by esDotDev** [comment]
This is fixed in the latest build
